# Generated by Django 5.2.17 on 2026-09-08 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('slack', 'Slack'), ('discord', 'Discord'), ('whatsapp_business', 'WhatsApp Business'), ('imessage', 'iMessage')], max_length=32)),
                ('external_account', models.CharField(help_text='Identifier at the provider, e.g. an address, workspace, or handle.', max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Error'), ('revoked', 'Revoked')], default='connected', max_length=16)),
                ('read_only', models.BooleanField(default=True)),
                ('token_ref', models.CharField(blank=True, help_text='Opaque pointer to credentials held in a secrets store. No token material is ever written to this table.', max_length=200)),
                ('included_scopes', models.JSONField(blank=True, default=list, help_text='Which channels/labels/chats count, e.g. [{"id":"C08KJ21X","name":"#engineering","type":"channel"}]. Excluded scopes are simply absent.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['space', 'provider', 'external_account'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('handles', models.JSONField(blank=True, default=list, help_text='Provider identities, e.g. ["priya@work.com", "@priya"].')),
                ('is_vip', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_vip', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text="The provider's own message id.", max_length=200)),
                ('scope_name', models.CharField(blank=True, help_text='Channel/label the message arrived in, denormalized from the provider.', max_length=200)),
                ('sent_at', models.DateTimeField()),
                ('body', models.TextField()),
                ('permalink', models.URLField(blank=True)),
                ('is_noise', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='unopsis.connection')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='unopsis.person')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal')], max_length=16)),
                ('detail_level', models.IntegerField(default=3, help_text='1 = a single line per item, 5 = a full recap.')),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('deliver_in_app', models.BooleanField(default=True)),
                ('deliver_email', models.BooleanField(default=True)),
                ('deliver_chat_dm', models.BooleanField(default=False)),
                ('digest_times', models.JSONField(blank=True, default=list, help_text='When to build, e.g. ["08:00", "16:30"]. Weekday-only by convention.')),
                ('rules', models.JSONField(blank=True, default=list, help_text='Always/never surface instructions, e.g. [{"mode":"always","target":"person","value":"Prof. Ramirez"}].')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'kind'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='unopsis.space'),
        ),
        migrations.AddField(
            model_name='connection',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='unopsis.space'),
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('on_demand', 'On demand')], max_length=16)),
                ('status', models.CharField(choices=[('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed')], default='building', max_length=16)),
                ('headline', models.CharField(blank=True, help_text='The one line at the top, e.g. "Three things need you before noon."', max_length=200)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('topic_count', models.PositiveIntegerField(default=0)),
                ('read_seconds', models.PositiveIntegerField(default=0, help_text='Estimated time to read.')),
                ('steps', models.JSONField(blank=True, default=list, help_text='Generation progress for the waiting screen, e.g. [{"label":"Reading 212 messages","status":"done","ms":3100}].')),
                ('model_version', models.CharField(blank=True, max_length=80)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='unopsis.space')),
            ],
            options={
                'ordering': ['-window_end'],
            },
        ),
        migrations.CreateModel(
            name='BriefItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The subject this item is about.', max_length=200)),
                ('lane', models.CharField(choices=[('needs_you', 'Needs you'), ('moving', 'Moving without you'), ('fyi', 'FYI')], max_length=16)),
                ('rank', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('why', models.TextField(blank=True, help_text='Why this surfaced -- shown on demand.')),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('handled', 'Handled'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('actions', models.JSONField(blank=True, default=list, help_text='Offered actions, e.g. [{"kind":"reply","label":"Reply to Prof. Ramirez","primary":true}].')),
                ('draft_body', models.TextField(blank=True, help_text='A reply composed but not yet sent.')),
                ('draft_sent_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('feedback', models.SmallIntegerField(default=0, help_text='-1 thumbs down, 0 none, +1 thumbs up.')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='unopsis.brief')),
                ('messages', models.ManyToManyField(blank=True, help_text="The receipts: every message this item's summary rests on.", related_name='brief_items', to='unopsis.message')),
                ('primary_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_for_items', to='unopsis.message')),
            ],
            options={
                'ordering': ['lane', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('brief', 'lane', 'rank'), name='uniq_slot_per_brief'), models.UniqueConstraint(fields=('brief', 'title'), name='uniq_title_per_brief')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['connection', 'sent_at'], name='idx_message_conn_sent'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('connection', 'external_id'), name='uniq_message_per_connection'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('user', 'kind'), name='uniq_space_per_user_kind'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('space', 'display_name'), name='uniq_person_per_space_name'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('space', 'provider', 'external_account'), name='uniq_connection_per_space_provider_account'),
        ),
        migrations.AddConstraint(
            model_name='brief',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger', 'scheduled')), fields=('space', 'window_start', 'window_end'), name='uniq_scheduled_brief_per_window'),
        ),
    ]
